# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rustyboy/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/193.5662.56/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/rustyboy/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/193.5662.56/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rustyboy/CLionProjects/convertor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rustyboy/CLionProjects/convertor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rustyboy/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/193.5662.56/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/rustyboy/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/193.5662.56/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustyboy/CLionProjects/convertor/CMakeFiles /home/rustyboy/CLionProjects/convertor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rustyboy/CLionProjects/convertor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named play

# Build rule for target.
play: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 play
.PHONY : play

# fast build rule for target.
play/fast:
	$(MAKE) -f CMakeFiles/play.dir/build.make CMakeFiles/play.dir/build
.PHONY : play/fast

#=============================================================================
# Target rules for targets named convertor

# Build rule for target.
convertor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convertor
.PHONY : convertor

# fast build rule for target.
convertor/fast:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/build
.PHONY : convertor/fast

src/InputForm.o: src/InputForm.cpp.o

.PHONY : src/InputForm.o

# target to build an object file
src/InputForm.cpp.o:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/InputForm.cpp.o
.PHONY : src/InputForm.cpp.o

src/InputForm.i: src/InputForm.cpp.i

.PHONY : src/InputForm.i

# target to preprocess a source file
src/InputForm.cpp.i:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/InputForm.cpp.i
.PHONY : src/InputForm.cpp.i

src/InputForm.s: src/InputForm.cpp.s

.PHONY : src/InputForm.s

# target to generate assembly for a file
src/InputForm.cpp.s:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/InputForm.cpp.s
.PHONY : src/InputForm.cpp.s

src/Logics.o: src/Logics.cpp.o

.PHONY : src/Logics.o

# target to build an object file
src/Logics.cpp.o:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/Logics.cpp.o
.PHONY : src/Logics.cpp.o

src/Logics.i: src/Logics.cpp.i

.PHONY : src/Logics.i

# target to preprocess a source file
src/Logics.cpp.i:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/Logics.cpp.i
.PHONY : src/Logics.cpp.i

src/Logics.s: src/Logics.cpp.s

.PHONY : src/Logics.s

# target to generate assembly for a file
src/Logics.cpp.s:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/Logics.cpp.s
.PHONY : src/Logics.cpp.s

src/UserInterface.o: src/UserInterface.cpp.o

.PHONY : src/UserInterface.o

# target to build an object file
src/UserInterface.cpp.o:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/UserInterface.cpp.o
.PHONY : src/UserInterface.cpp.o

src/UserInterface.i: src/UserInterface.cpp.i

.PHONY : src/UserInterface.i

# target to preprocess a source file
src/UserInterface.cpp.i:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/UserInterface.cpp.i
.PHONY : src/UserInterface.cpp.i

src/UserInterface.s: src/UserInterface.cpp.s

.PHONY : src/UserInterface.s

# target to generate assembly for a file
src/UserInterface.cpp.s:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/UserInterface.cpp.s
.PHONY : src/UserInterface.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/convertor.dir/build.make CMakeFiles/convertor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... play"
	@echo "... convertor"
	@echo "... src/InputForm.o"
	@echo "... src/InputForm.i"
	@echo "... src/InputForm.s"
	@echo "... src/Logics.o"
	@echo "... src/Logics.i"
	@echo "... src/Logics.s"
	@echo "... src/UserInterface.o"
	@echo "... src/UserInterface.i"
	@echo "... src/UserInterface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

